language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: 7.0
  
before_install:
  - pecl install pthreads-2.0.10
  - pecl install xdebug
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

before_script:
  - composer selfupdate

script:
  - ant composer-init
  - ant build
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: info@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
